## Dependencies
lanternlib_version_range=[2.1.1]

## Mod Properties
mod_id=blockreplacer
mod_name=Block Replacer
repo_name=BlockReplacer
mod_license=MIT
mod_version=1.0.2
mod_author=RedCraft86
mod_group_id=com.redcraft86.blockreplacer
mod_description=Simple utility mod to replace blocks with other blocks.
mod_credits=To anyone who may have contributed